### ISSUE TITLE
Help with locale

### ISSUE THREAD

**Issue by Jorgelig** [carlosribas/medvet#6]
Hello, I am translating the language pack to Spanish Mexico with Poedit ( https://poedit.net/).

But when trying to load the application I get this error; The text file with the translations is already there, but it seems to me that the problem is with the compiled package. Could you take a look and help me how can I fix it?

[PR](https://github.com/carlosribas/medvet/pull/5)

![image](https://user-images.githubusercontent.com/581672/216257519-1fe7ee60-34f7-4508-a388-73f3d47b6559.png)

**Comment by carlosribas** [comment]
Hi Jorge. 

Thank you for your interest in this software. Well, I imagine you've seen that it needs some updates. Unfortunately, I'm not working on it anymore. 

The good news is that your changes worked for me. 
<img width="1495" alt="Screenshot 2023-02-06 at 20 47 44" src="https://user-images.githubusercontent.com/8561563/217081789-fd1bcfad-3051-47b5-808b-e1d9498fed1f.png">

As you can see, if you want to keep the three languages, you will need to do a little change in the html/css

Please try to run the `compilemessages` command from the container:
1. docker ps
2. docker exec -it <container_id> bash
3. python manage.py compilemessages

Please let me know if you have any questions!

**Comment by Jorgelig** [comment]
When running it in the container I get these errors.

Is it better to delete the files and reload them?

<img width="902" alt="image" src="https://user-images.githubusercontent.com/581672/217416501-84f652b8-d116-49e2-aebc-444c7f80d2fd.png">

**Comment by Jorgelig** [comment]
Thanks for the commands, that fixed the problem. 

What do you think of merging my two PR?

https://github.com/carlosribas/medvet/pull/4
https://github.com/carlosribas/medvet/pull/5

**Comment by carlosribas** [comment]
Sure, I'll do that this weekend.

I forgot to say that there are some fields, such as zip code and phone number, which were configured according to the Brazilian standard. I can change them to accept any entries, but I won't promise I'll do that this weekend :)

By the way, what are your plans for this system?

**Comment by carlosribas** [comment]
Done. I'll close this issue, but feel free to create a new one if you have any problems
